[package]
name = "over-there-auth"
version = "0.1.0"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"

[dependencies]
hmac = "0.7.1"
sha2 = "0.8.0"
serde = { version = "1.0.103", features = ["derive"] }
serde-big-array = "0.2.0"
over-there-utils = { path = "../over-there-utils" }
