[package]
name = "over-there"
description = "Tool to enable software management and execution remotely from \"over there.\""
version = "0.1.0"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"

[dependencies]
clap = "~2.33.0"
ring = "0.16.9"
